### PR TITLE
Amazon collector full refresh

### PR DESCRIPTION
**Pull request by slemrmartin**
Amazon collector is based on more generic code. 
Entities are generating hash with values and reference values(uids).
Parser defines and transforms  values to lazy objects.
Storage defines parent and children collections.

### CODE REVIEW

**Comment by slemrmartin** [comment]
cc @Ladas

**Comment by agrare** [comment]
Nice @slemrmartin !

So with this being a different collector binary we'd need a new pod for the amazon mock source.  Originally I was thinking we should just send all inventory types for the single mock source but this makes sense too.

**Review by agrare — APPROVED** [review]
Looks great

**Comment by slemrmartin** [comment]
@agrare I'll continue with mock-openshift refactoring. Then it'll be easy to send separate or combined data, it'll be just one simple definition

**Comment by agrare** [comment]
@slemrmartin :+1: sounds good

**Pull request merged**
