### PR TITLE
Changed "amounts" to "data" arg

### PR DESCRIPTION
**Pull request by slemrmartin**
`bin/mock-collector --amounts` changed to `bin/mock-collector --data`
`config/amounts` renamed to `config/data`

This is needed because of data config will specify more than amounts. It'll be extended by custom data values.

---

**dependents**:
- https://github.com/slemrmartin/topological_inventory-guides/pull/10
- https://github.com/ManageIQ/topological_inventory-deploy/pull/48

### CODE REVIEW

**Comment by slemrmartin** [comment]
@agrare pls review

**Comment by slemrmartin** [comment]
@carbonin is somewhere deployment config (except ^^) for mock source which has to be changed?

**Comment by carbonin** [comment]
@slemrmartin No, the deploy repo is the only one with the mock source deployment config definition.

**Review by Ladas — APPROVED** [review]
:+1:

**Pull request merged**
