### PR TITLE
[WIP] Payload for Inventory Upload svc

### PR DESCRIPTION
**Pull request by slemrmartin**
Usage: 
`bin/mock-collector-inventory-upload --source=5eebe172-7baa-4280-823f-19e597d091e9 --config=simple --data=openshift/small`

There are two possibilities:
1) Collect everything on CF, gzip it and upload
2) Use collector class and save & sweep in chunks (used here)

### CODE REVIEW

**Comment by slemrmartin** [comment]
@agrare I think option 2) is ok, if we set default_limit to higher number than in normal collector.

**Comment by syncrou** [comment]
@slemrmartin can we get the conflicts resolved?

**Comment by slemrmartin** [comment]
@syncrou question is if it's worth to do it. This was a demonstration how to send collectors data as a tar file through insights-upload service -> topological sync  and I'm not sure if we'll use it

**Comment by syncrou** [comment]
@slemrmartin should we just close it?

**Comment by slemrmartin** [comment]
closing

**Pull request closed without merging**
